tabs:
    fields:

        ####################################################
        # Tab: Nav
        ####################################################
        nav_section:
            tab: Menu
            label: Menu
            type: section
        nav_logo:
            tab: Menu
            label: Logo pro světlou variantu webu
            type: fileupload
            mode: image
            span: left
        nav_logo_dark:
            tab: Menu
            label: Logo pro tmavou variantu webu
            type: fileupload
            mode: image
            span: right
        nav_logo_height:
            tab: Menu
            label: Výška loga
            type: number
            default: 40
        ####################################################
        # Tab: Footer
        ####################################################
        footer_section:
            tab: Patička
            label: Patička
            type: section
        footer_cols_section:
            tab: Patička
            label: Obsah
            type: section
        footer_cols:
            tab: Patička
            prompt: Přidat obsah
            titleFrom: footer_col_section
            type: repeater
            form:
                fields:
                    footer_col_size:
                        label: Velikost
                        type: balloon-selector
                        span: full
                        options:
                            col-lg-12 col-md-12: Celá šířka
                            col-lg-6 col-md-12: 1/2 šířky
                            col-lg-4 col-md-12: 1/3 šířky
                            col-lg-3 col-md-12: 1/4 šířky
                    footer_col_text:
                        label: Obsah
                        type: richeditor
                        size: small
                        span: full